db:
  image: postgres:9.4
  ports:
    - "5432"

redis:
  image: redis
  ports:
    - "6379"

sidekiq:
  build: .
  command: bundle exec sidekiq
  links:
    - db
    - redis

web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db
    - redis
